const startScreen=document.querySelector("#start-screen"),gameScreen=document.querySelector("#game-screen"),playButton=document.querySelector("#play-button"),player=document.querySelector("#player"),cookingStatus=document.querySelector("#cooking-status"),cookingStatusLabel=document.querySelector("#cooking-status-label"),cookingProgress=document.querySelector("#cooking-progress"),heldItem=document.querySelector("#held-item"),promptElement=document.querySelector("#interaction-prompt"),timerElement=document.querySelector("#timer"),scoreElement=document.querySelector("#score"),orderName=document.querySelector("#order-name"),orderDetail=document.querySelector("#order-detail"),orderTimer=document.querySelector("#order-timer"),message=document.querySelector("#game-message");
const heldItemIcons={ingredients:"#held-ingredients",cooking:"#held-cooking",soup:"#held-soup",stirFry:"#held-stir-fry"};
const objects=[...document.querySelectorAll(".object")].map((element)=>({element,name:element.dataset.object,x:Number(element.dataset.x),y:Number(element.dataset.y)}));
const menus=[{name:"Garden Soup",tool:"pot"},{name:"Sizzling Stir-Fry",tool:"pan"}];
const playerState={x:500,y:350,speed:4.5,radius:32}; const keys=new Set(); let score=0,secondsLeft=40,orderSecondsLeft=15,currentOrder,inventory="empty",cooking=false,timerId,orderTimerId,animationId,cookingTimeoutId,cookingAnimationId,cookingStartedAt,cookingTool,gameRunning=false;
function setPlayerPosition(){player.setAttribute("transform",`translate(${playerState.x} ${playerState.y})`)}
function updateCookingStatus(progress,label){cookingProgress.setAttribute("width",`${106*progress}`);cookingStatusLabel.textContent=label;cookingStatus.setAttribute("opacity", "1")}
function hideCookingStatus(){window.cancelAnimationFrame(cookingAnimationId);cookingStatus.setAttribute("opacity","0");cookingProgress.setAttribute("width","0");cookingStatusLabel.textContent="COOKING";cookingTool=null}
function animateCooking(){const progress=Math.min(1,(performance.now()-cookingStartedAt)/2000);updateCookingStatus(progress,"COOKING");if(progress<1)cookingAnimationId=window.requestAnimationFrame(animateCooking)}
function positionCookingStatus(){if(cookingTool){const object=objects.find((item)=>item.name===cookingTool);if(object)cookingStatus.setAttribute("transform",`translate(${object.x} ${object.y})`)}}
function updateHeldItem(){Object.values(heldItemIcons).forEach((selector)=>document.querySelector(selector).setAttribute("opacity","0"));let icon=null;if(inventory==="ingredients")icon=heldItemIcons.ingredients;if(inventory==="cooking")icon=heldItemIcons.cooking;if(inventory===`cooked-${menus[0].name}`)icon=heldItemIcons.soup;if(inventory===`cooked-${menus[1].name}`)icon=heldItemIcons.stirFry;heldItem.setAttribute("opacity",icon?"1":"0");if(icon)document.querySelector(icon).setAttribute("opacity","1")}
function nearestObject(){return objects.reduce((nearest,object)=>{const distance=Math.hypot(playerState.x-object.x,playerState.y-object.y);return distance<nearest.distance?{object,distance}:nearest},{object:null,distance:Infinity})}
function setMessage(text){message.textContent=text}
function updateOrder(){orderName.textContent=currentOrder.name;orderDetail.textContent=`Cook with the ${currentOrder.tool}, then serve it.`;orderTimer.textContent=orderSecondsLeft;orderTimer.classList.toggle("warning",orderSecondsLeft<=5)}
function generateOrder(){currentOrder=menus[Math.floor(Math.random()*menus.length)];orderSecondsLeft=15;updateOrder()}
function clearInventory(){inventory="empty";cooking=false;window.clearTimeout(cookingTimeoutId);hideCookingStatus();updateHeldItem()}
function expireOrder(){clearInventory();generateOrder();setMessage("The customer left. A new order is ready.")}
function updatePrompt(){const nearest=nearestObject(),close=nearest.object&&nearest.distance<playerState.radius+72;if(!close){promptElement.setAttribute("opacity","0");return} promptElement.setAttribute("transform",`translate(${nearest.object.x} ${nearest.object.y-95})`);promptElement.setAttribute("opacity","1");const labels={ingredients:"collect ingredients",pot:"cook with the pot",pan:"cook with the pan",serve:"serve the menu"};setMessage(`Press E to ${labels[nearest.object.name]}.`)}
function cook(tool){if(cooking){setMessage("Cooking is already in progress.");return}if(inventory!=="ingredients"){setMessage("Collect the ingredients first.");return}if(currentOrder.tool!==tool){setMessage(`This order needs the ${currentOrder.tool}, not the ${tool}.`);return}cooking=true;inventory="cooking";cookingTool=tool;cookingStartedAt=performance.now();positionCookingStatus();window.cancelAnimationFrame(cookingAnimationId);updateCookingStatus(0,"COOKING");cookingAnimationId=window.requestAnimationFrame(animateCooking);updateHeldItem();setMessage(`Cooking with the ${tool}... 2 seconds.`);cookingTimeoutId=window.setTimeout(()=>{cooking=false;inventory="ready";updateCookingStatus(1,"READY");setMessage(`Your ${currentOrder.name} is ready. Pick it up from the ${cookingTool}.`);updatePrompt()},2000)}
function interact(){if(!gameRunning)return;const nearest=nearestObject();if(!nearest.object||nearest.distance>=playerState.radius+72){setMessage("Move closer to a kitchen station first.");return}const name=nearest.object.name;if(name==="ingredients"){if(inventory==="empty"){inventory="ingredients";updateHeldItem();setMessage("Ingredients collected. Follow the customer order.")}else setMessage("Your hands are already full.");return}if(name==="pot"||name==="pan"){if(inventory==="ready"){if(name===cookingTool){inventory=`cooked-${currentOrder.name}`;hideCookingStatus();updateHeldItem();setMessage(`You picked up the ${currentOrder.name}. Take it to the serve point.`)}else setMessage(`Your menu is ready at the ${cookingTool}.`)}else cook(name);return}if(inventory===`cooked-${currentOrder.name}`){score++;scoreElement.textContent=score;clearInventory();generateOrder();setMessage("Order served! A new customer is waiting.")}else if(inventory==="cooking")setMessage("The food is still cooking.");else setMessage("Cook the ordered menu before serving it.")}
function movePlayer(){if(!gameRunning)return;let dx=0,dy=0;if(keys.has("arrowleft")||keys.has("a"))dx--;if(keys.has("arrowright")||keys.has("d"))dx++;if(keys.has("arrowup")||keys.has("w"))dy--;if(keys.has("arrowdown")||keys.has("s"))dy++;if(dx||dy){const length=Math.hypot(dx,dy);playerState.x=Math.max(65,Math.min(935,playerState.x+dx/length*playerState.speed));playerState.y=Math.max(105,Math.min(555,playerState.y+dy/length*playerState.speed));setPlayerPosition();positionCookingStatus();updatePrompt()}animationId=requestAnimationFrame(movePlayer)}
function endGame(){gameRunning=false;clearInventory();cancelAnimationFrame(animationId);clearInterval(timerId);clearInterval(orderTimerId);window.setTimeout(()=>{gameScreen.hidden=true;startScreen.hidden=false},700)}
function startGame(){startScreen.hidden=true;gameScreen.hidden=false;gameRunning=true;score=0;secondsLeft=40;scoreElement.textContent=score;timerElement.textContent=secondsLeft;timerElement.classList.remove("warning");playerState.x=500;playerState.y=350;clearInventory();generateOrder();setPlayerPosition();positionCookingStatus();updatePrompt();clearInterval(timerId);clearInterval(orderTimerId);timerId=window.setInterval(()=>{secondsLeft--;timerElement.textContent=secondsLeft;if(secondsLeft<=10)timerElement.classList.add("warning");if(secondsLeft<=0)endGame()},1000);orderTimerId=window.setInterval(()=>{orderSecondsLeft--;updateOrder();if(orderSecondsLeft<=0)expireOrder()},1000);cancelAnimationFrame(animationId);animationId=requestAnimationFrame(movePlayer)}
window.addEventListener("keydown",(event)=>{const key=event.key.toLowerCase();if(["arrowleft","arrowright","arrowup","arrowdown"," "].includes(key))event.preventDefault();if(key==="e")interact();keys.add(key)});window.addEventListener("keyup",(event)=>keys.delete(event.key.toLowerCase()));playButton.addEventListener("click",startGame);